name: Build & Publish Notebook Servers
on:
  push:
    branches:
      - master
      - v*-branch
    paths:
      - components/example-notebook-servers/**
      - releasing/version/VERSION
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: false

jobs:
  base_images:
    name: Build & Push - Base
    uses: ./.github/workflows/example_notebook_servers_publish_TEMPLATE.yaml
    secrets: inherit
    with:
      build_arch: linux/amd64,linux/arm64
      image_folders: |
        base

  jupyter_images:
    name: Build & Push - Jupyter
    uses: ./.github/workflows/example_notebook_servers_publish_TEMPLATE.yaml
    needs: [ base_images ]
    secrets: inherit
    with:
      build_arch: linux/amd64,linux/arm64
      image_folders: |
        jupyter

  jupyter_tensorflow_cuda_images:
    name: Build & Push - Jupyter (TensorFlow + CUDA)
    uses: ./.github/workflows/example_notebook_servers_publish_TEMPLATE.yaml
    needs: [ jupyter_images ]
    secrets: inherit
    with:
      # TODO: support 'linux/arm64' for TensorFlow CUDA images
      build_arch: linux/amd64
      image_folders: |
        jupyter-tensorflow-cuda
        jupyter-tensorflow-cuda-full
